// <auto-generated />
namespace ASample.Web.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updateAppuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAppuser));
        
        string IMigrationMetadata.Id
        {
            get { return "201802070735586_updateAppuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
